name: Generate Nix Hash
description: Github Action to write a JSON file with rev and sha256 of given repository revision.
author: Tobias Happ
inputs:
  myInput:              # change this
    description: 'input description here'
    default: 'default value if applicable'
runs:
  using: 'node12'
  main: 'dist/index.js'
